<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VR92I9TB" failures="1" tests="3" name="Test" time="10.615" errors="0" timestamp="2025-09-12T10:27:24 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_registration" time="1.7"/>
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="1.295"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at utilities.DataProviders.geteData(DataProviders.java:24)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
